config/routes.rb
Rails.application.routes.draw do
  devise_for :users
# *1
  resources :messages do |message|
    resources :comments
  end 
# **
  root 'messages#index'

end

# 1)Les commentaires 'appartiennent' aux messages => nested resource 
#   On le voit bien dans les routes ex: 

#     message_comment GET    /messages/:message_id/comments/:id(.:format)      comments#show

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :title, :description, presence: { message: ": ce champ doit être renseigné." }
  belongs_to :user 
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages
  has_many :comments 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message 
  before_action :find_comment, only:[:edit, :update, :destroy]
  before_action :authenticate_user!


  def create 
    @comment = @message.comments.create(comment_params)#2*
    @comment.user_id = current_user.id #4*

    if @comment.save
      redirect_to message_path(@message)
    end 
  end 

  def edit 
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else 
      render 'edit'
    end 
  end 
  
  def destroy 
    @comment.destroy
      redirect_to message_path
  end

  private 
    def comment_params  #3*
      params.require(:comment).permit(:content)
    end 

    def find_message
      @message = Message.find(params[:message_id])
    end

    def find_comment
      @comment = @message.comments.find(params[:id])
    end
end

# 1 : trouver le message qui est à la source du commentaire
# 2 : Créer un commentaire relatif à ce message 
# 3 : definir la methode qui contient les attributs nécessaires à la création d'un commentaire.
# 4 : Lier le commentaire à son auteur (l'utilisateur actuel)

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @messages = Message.all.order("created_at DESC")
  end 

  def show

  end 
# Ensure each message is linked to its author => current_user.messages.build (association)
  def new
    @message = current_user.messages.build
  end 

  def create 
    @message = current_user.messages.build(message_params)
    if @message.save 
      redirect_to root_path 
    else 
      render 'new'
    end 
  end 
  def edit
  end 

  def update 
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end 
  end 

  def destroy
    @message.destroy 
    redirect_to root_path
  end 
  private 

  def message_params 
    params.require(:message).permit(:title, :description)
  end     

  def find_message 
    @message = Message.find(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<h3> <%= comment.content %> </h3>
<p>Posted by <%= comment.user.email%> <%= time_ago_in_words(comment.created_at) %></p>

<% if user_signed_in? %>
  <%if current_user.id == comment.user_id %>
    <%= link_to 'modifier', edit_message_comment_path(comment.message, comment)  %><%# *1 %>
    <%= link_to 'effacer', message_comment_path(comment.message, comment), method: :delete,
    data: { confirm: "Confirmer la suppression?"} 
    %>
  <% end %>
<% end %>

<%# 1) Nous spécifions 
  * le message concerné par le commentaire, qui apparaitra en premier dans l'url (messages/3... par exemple)
  * le commentaire concerné par rapport aux autres commentaires (messages/3/comments/2) 
  %>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label:"Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Modifier commentaire</h1>
<%= simple_form_for ([@message, @comment]) do |f| %>
  <%= f.input :content, label: "Commentaire" %>
  <%= f.button :submit %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-default">
      <div class="container">
        
        <div class="navbar-header">
        <%= link_to 'Message Board', root_path, class: "navbar-brand" %>
        </div>
        
        <ul class="nav navbar-nav">
          <li> <%= link_to "Inscription", new_user_registration_path %> </li>          
        <!-- si l'utilisateur est connecté: lui propose de se déconnecter, et inversement-->
          <% if user_signed_in? %>
            <li> <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li> <%= link_to "Connexion", new_user_session_path %></li>
          <% end %>
        </ul>
        
        <!-- si l'utilisateur est connecté, lui propose d'écrire un nouveau message -->
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Nouveau message", new_message_path, class:"navbar-link"%></li>
            <% end %>
        </ul>
        
    </div>
  </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f|%>
  <%= f.input :title, label: 'Message title' %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<%= render "form" %>

app/views/messages/index.html.erb
<% @messages.each do |message|%>
  
  <h2><%= message.title%> </h2>
  <!-- <h2><%= message.description%> </h2> -->

  <%= link_to 'Ecrire un message', new_message_path, class:"btn btn-success" %>
  <%= link_to 'Voir message', message_path(message), class:"btn btn-default" %>

<% end %>

app/views/messages/new.html.erb
<%= render 'form'%>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2>
<p> Ajouté par <%= @message.user.email%> <%= time_ago_in_words(@message.created_at) %></p>
<h2><%= @message.description%></h2>

<h2>Commentaires: </h2>

<%= render @message.comments %> <!-- *1 -->

<h3>Répondre au message</h3>
<%= render 'comments/form' %>

<%= link_to 'Retour', root_path %>
<% if user_signed_in?%>
  <% if @message.user_id == current_user.id %>
    <%= link_to 'Modifier', edit_message_path(@message) %>
    <%= link_to 'Effacer', message_path(@message), method: :delete, data: {confirm: "Confirmez-vous la suppression?"} %>
  <% end %>
<% end %>
<!-- *l'utilisation d'un partial (ici: _comments) permet de ne pas avoir à itérer sur tous 
      les commentaires liés au message avec une boucle.  -->